# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-25 01:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0007_auto_20171024_1220'),
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=150, verbose_name='Название')),
                ('datetime', models.DateTimeField(verbose_name='Дата')),
                ('type', models.IntegerField(choices=[(0, 'Ошибка'), (1, 'Информация'), (2, 'Предупреждение')], default=1, verbose_name='Задача')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активная')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Изменен')),
                ('service_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.ServicePoint')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.Task')),
            ],
            options={
                'verbose_name': 'Лог',
                'verbose_name_plural': 'Логи',
            },
        ),
    ]
