# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-30 05:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='service_point',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.ServicePoint'),
        ),
        migrations.AlterField(
            model_name='log',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tasks.Task'),
        ),
    ]
