# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-10 04:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slacknotice',
            name='description',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Комментарий'),
        ),
    ]
