# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-25 01:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0007_auto_20171024_1220'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='Название')),
                ('task', models.CharField(choices=[('synctime', 'Синхронизация времени на Linux')], default='synctime', max_length=100, verbose_name='Задача')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активная')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Изменен')),
                ('service_point', models.ManyToManyField(to='main.ServicePoint')),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
            },
        ),
    ]
