#copy to root folder project

django:
  restart: always
  build: .
  ports:
    - 8000:8000
  volumes:
#    - ./sr—Å:/app/src
    - ../devops/envfiles/.env:/app/.env
    - ./db.sqlite3:/app/db.sqlite3:rw