# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-02 05:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20170802_1227'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personal',
            options={'verbose_name': 'Сотрудник АЗК', 'verbose_name_plural': 'Сотрудники АЗК'},
        ),
        migrations.AlterField(
            model_name='azs',
            name='full_name',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='Полное наименование'),
        ),
    ]
