# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-24 01:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20170802_1351'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacteristicSP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value1', models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Значение 1')),
                ('value2', models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Значение 2')),
                ('value3', models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Значение 3')),
                ('value4', models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Значение 4')),
                ('description', models.TextField(blank=True, default=None, null=True, verbose_name='Комментарий')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Изменен')),
                ('azs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Azs')),
            ],
            options={
                'verbose_name': 'Характеристика АРМ',
                'verbose_name_plural': 'Характеристики АРМ',
            },
        ),
        migrations.CreateModel(
            name='ServicePoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, default=None, null=True, verbose_name='Комментарий')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Изменен')),
                ('azs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Azs')),
            ],
            options={
                'verbose_name': 'АРМ',
                'verbose_name_plural': 'Точки обслуживания',
            },
        ),
        migrations.CreateModel(
            name='TypeCharacteristicSP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='Название')),
                ('type', models.IntegerField(choices=[(0, 'IP адрес'), (1, 'Операционная система')], default=-1)),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Изменен')),
            ],
            options={
                'verbose_name': 'Тип характеристики АРМ',
                'verbose_name_plural': 'Названия характеристик АРМ',
            },
        ),
        migrations.CreateModel(
            name='TypeServicePoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Тип АРМ',
                'verbose_name_plural': 'Названия АРМ',
            },
        ),
        migrations.AddField(
            model_name='servicepoint',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.TypeServicePoint'),
        ),
        migrations.AddField(
            model_name='characteristicsp',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.TypeCharacteristicSP'),
        ),
    ]
