# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-24 02:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20171024_0914'),
    ]

    operations = [
        migrations.AddField(
            model_name='typeservicepoint',
            name='type',
            field=models.IntegerField(choices=[(-1, 'Другое'), (0, 'Система управления'), (1, 'Касса'), (2, 'Контроллер')], default=-1, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='typecharacteristicsp',
            name='type',
            field=models.IntegerField(choices=[(-1, 'Другое'), (0, 'IP адрес'), (1, 'Операционная система')], default=-1, verbose_name='Тип'),
        ),
    ]
