# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-24 03:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20171024_1024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='characteristicsp',
            name='azs',
        ),
        migrations.AddField(
            model_name='characteristicsp',
            name='service_point',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.ServicePoint'),
            preserve_default=False,
        ),
    ]
