# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-25 02:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20171024_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicepoint',
            name='azs',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Azs', verbose_name='АЗК/АЗС'),
        ),
        migrations.AlterField(
            model_name='servicepoint',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.TypeServicePoint', verbose_name='Тип АРМ'),
        ),
    ]
