# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-07 08:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20171207_1602'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employeesazk',
            options={'verbose_name': 'Сотрудник АЗК', 'verbose_name_plural': 'Сотрудники АЗК'},
        ),
        migrations.RemoveField(
            model_name='employeesazk',
            name='name',
        ),
        migrations.AddField(
            model_name='employeesazk',
            name='login',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Логин'),
        ),
        migrations.AddField(
            model_name='employeesazk',
            name='password',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Пароль'),
        ),
    ]
