# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-07 08:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20171207_1615'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeesazk',
            name='position',
        ),
    ]
