# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-07 08:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20171207_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeesazk',
            name='status',
            field=models.IntegerField(choices=[(-1, 'В обработке'), (0, 'Активный'), (1, 'Заблокированный')], default=-1, verbose_name='Статус'),
        ),
    ]
