# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-30 05:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20171207_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='phone',
            field=models.IntegerField(blank=True, default=None, max_length=10, null=True, verbose_name='Телефон'),
        ),
        migrations.AddField(
            model_name='person',
            name='telegram_id',
            field=models.IntegerField(blank=True, default=None, max_length=10, null=True, verbose_name='ID telegram'),
        ),
        migrations.AlterField(
            model_name='azs',
            name='azs_group',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.AzsGroup', verbose_name='Группа'),
        ),
        migrations.AlterField(
            model_name='azs',
            name='manager',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.Personal', verbose_name='Менеджер'),
        ),
        migrations.AlterField(
            model_name='characteristicsp',
            name='service_point',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.ServicePoint'),
        ),
        migrations.AlterField(
            model_name='characteristicsp',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.TypeCharacteristicSP'),
        ),
        migrations.AlterField(
            model_name='employeesazk',
            name='azk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.Azs', verbose_name='АЗК'),
        ),
        migrations.AlterField(
            model_name='employeesazk',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.Person', verbose_name='Физ. лицо'),
        ),
        migrations.AlterField(
            model_name='employeesazk',
            name='position',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.Position', verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='invent',
            name='azs',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.Azs'),
        ),
        migrations.AlterField(
            model_name='servicepoint',
            name='azs',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.Azs', verbose_name='АЗК/АЗС'),
        ),
        migrations.AlterField(
            model_name='servicepoint',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.TypeServicePoint', verbose_name='Тип АРМ'),
        ),
    ]
