# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-30 05:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20180130_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='phone',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Телефон'),
        ),
    ]
