# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-06 03:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20180130_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='telegram_id',
            field=models.IntegerField(blank=True, default=None, null=True, unique=True, verbose_name='ID telegram'),
        ),
    ]
